version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: studydb
      POSTGRES_USER: stephen
      POSTGRES_PASSWORD: buddydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
